spring:
  profiles:
    active: dev

---

spring:
  profiles:
    default: prod
---

spring:
  profiles:
    include: test
    
---

spring:
  config.activate.on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///apurbadb
    username: root
    
---

spring:
  config.activate.on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql:///apurbadb
    username: root
    
---

spring:
  config.activate.on-profile: uat
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: apurba
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    
---

spring:
  config.activate.on-profile: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: apurba
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system


  